version: "3"
services:
  # db:
  #   container_name: postgresql_13
  #   hostname: db
  #   image: postgres:13
  #   volumes:
  #     - ./data/:/docker-entrypoint-initdb.d/
  #     - postgres_data:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_PASSWORD=password
  #     - POSTGRES_HOST_AUTH_METHOD=trust
  #   tty: true
  #   restart: always
  srv_blue:
    container_name: odoo_15_blue
    build:
      context: .
      dockerfile: Dockerfile
    # image: hikari141/srv:${ODOO_VERSION}
    # depends_on:
    #   - db
    restart: always
    volumes:
      - type: bind
        source: ./unit_test
        target: /mnt/extras
      - odoo_data:/opt/odoo/.local/share/Odoo
      - .:/mnt/source
    tty: true

  srv_green:
    container_name: odoo_15_green
    build:
      context: .
      dockerfile: Dockerfile
    # image: hikari141/srv:${ODOO_VERSION}
    # depends_on:
    #   - db
    restart: always
    volumes:
      - type: bind
        source: ./unit_test
        target: /mnt/extras
      - odoo_data:/opt/odoo/.local/share/Odoo
      - .:/mnt/source
    tty: true
  
  proxy:
    container_name: nginx1
    image: nginx
    depends_on:
      - srv_blue
      - srv_green
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
    ports:
      - '80:80'
    tty: true

volumes:
  odoo_data:
  unit_test:
  # postgres_data: