version: "3"
services:
  srv:
    container_name: odoo_15
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - type: bind
        source: unit_test
        target: /mnt/extras
      - odoo_data:/opt/odoo/.local/share/Odoo
      - .:/mnt/source
    tty: true

volumes:
  odoo_data:
  unit_test: